version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./sqldump/:/docker-entrypoint-initdb.d/
      - ./mysql_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: biznes_elektroniczny
      MYSQL_USER: biznes_elektroniczny
      MYSQL_PASSWORD: toor

  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080

  prestashop:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/Biznes_Elektroniczny/

