version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./sqldump/:/docker-entrypoint-initdb.d/
      - ./mysql_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: biznes_elektroniczny
      MYSQL_USER: biznes_elektroniczny
      MYSQL_PASSWORD: toor

  phpmyadmin:
    image: phpmyadmin:5.0.4
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_USER: biznes_elektroniczny
      MYSQL_PASSWORD: toor

  prestashop1:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "180:80"

  prestashop2:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "220:80"

  nginx:
    build: nginx-docker
    restart: always
    depends_on:
      - prestashop1
      - prestashop2
    ports:
      - "80:80"
      - "443:443"

